version: "3.8"
services:
  minio:
    image: minio/minio:RELEASE.2025-01-01T00-00-00Z
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  ingestion-service:
    build: ./ingestion-service
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: "http://minio:9000"
      BUCKET_NAME: "raw-data"
    ports:
      - "8001:8000"

  batch-processing:
    build: ./batch-processing
    depends_on:
      - minio
    command: ["bash","-c","sleep 5 && python process.py"]

  delivery-api:
    build: ./delivery-api
    depends_on:
      - minio
    ports:
      - "8002:8000"

volumes:
  minio_data:
