services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: ./.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_REGION: ${MINIO_REGION}
    volumes:
      - ../volumes/minio:/data

  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    env_file: ./.env
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb --ignore-existing local/${MINIO_BUCKET_RAW} &&
      mc mb --ignore-existing local/${MINIO_BUCKET_CURATED} &&
      mc mb --ignore-existing local/${MINIO_BUCKET_AGG} &&
      exit 0
      "

  postgres:
    image: postgres:16-alpine
    env_file: ./.env
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.9.3
    depends_on:
      - postgres
      - minio
    env_file: ./.env
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/requirements.txt:/requirements.txt
      - ../volumes/airflow:/opt/airflow
    command: webserver
    ports:
      - "8081:8080"

  airflow-scheduler:
    image: apache/airflow:2.9.3
    depends_on:
      - airflow-webserver
    env_file: ./.env
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/requirements.txt:/requirements.txt
      - ../volumes/airflow:/opt/airflow
    command: scheduler

  spark:
    image: apache/spark:3.5.1
    container_name: spark-master
    environment:
      SPARK_MODE: master
      SPARK_NO_DAEMONIZE: "true"
    ports:
      - "7077:7077"
      - "8082:8080"
    volumes:
      - ../services/preprocess/spark_app:/opt/spark-apps

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    depends_on:
      - spark
    environment:
      SPARK_MODE: worker
      SPARK_NO_DAEMONIZE: "true"
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ../services/preprocess/spark_app:/opt/spark-apps

  ingest:
    build:
      context: ../services/ingest     # âœ… FIXED PATH
    env_file: ./.env
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_BUCKET_RAW: ${MINIO_BUCKET_RAW}
    volumes:
      - ../data_source:/data_source:ro
    depends_on:
      - minio

  delivery:
    build:
      context: ../services/delivery
    env_file: ./.env
    environment:
        MINIO_ENDPOINT: ${MINIO_ENDPOINT}
        MINIO_BUCKET_AGG: ${MINIO_BUCKET_AGG}
        MINIO_REGION: ${MINIO_REGION}
        DELIVERY_PORT: ${DELIVERY_PORT}
    ports:
        - "${DELIVERY_PORT}:8080"
    depends_on:
        - minio
